'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5466
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Computer_Info.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _39() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_39", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _564651345() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_564651345", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _Date() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_Date", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Apple_Rainbow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Apple_Rainbow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Bye() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Bye", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Debian() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Debian", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property E() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("E", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property E0() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("E0", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Etoile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Etoile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fedora() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fedora", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Finder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Finder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Freespire() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Freespire", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fs() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("fs", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Globe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Globe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Gnome() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gnome", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property HD() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("HD", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property img0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property info() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("info", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property K() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("K", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property KDE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KDE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property kk() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("kk", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Konqueror() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Konqueror", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ky() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ky", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Linux() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Linux", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ln() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ln", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Mandriva() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mandriva", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Mouse() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mouse", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MouseL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MouseL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MouseM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MouseM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MouseR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MouseR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property My_Computer() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("My_Computer", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property need_for_speed_world_wide() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("need_for_speed_world_wide", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property O() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("O", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property OO() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("OO", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property R() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("R", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Refreshed() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Refreshed", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property RF() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("RF", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Rights() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Rights", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property RS() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("RS", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Screen() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Screen", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property sp() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("sp", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property StartupF() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("StartupF", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property StartupS() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("StartupS", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Stats() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Stats", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Temporary() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Temporary", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Time() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Time", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Ubuntu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ubuntu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property untitled() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("untitled", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property V() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("V", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Web() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Web", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Welcome() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Welcome", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Windows() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Windows", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Windows1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Windows1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
